package com.lactaoen.model;

public enum Set {
    CORE,
    AWESOME_LEVEL_9000,
    SCIENCE_FICTION_DOUBLE_FEATURE,
    BIG_GEEKY_BOX,
    MONSTER_SMASH,
    PRETTY_PRETTY_SMASH_UP,
    ITS_YOUR_FAULT,
    CEASE_AND_DESIST
}
